### ISSUE TITLE
API refactoring for 2.0

### ISSUE THREAD

**Issue by lstrojny** [php-amqp/php-amqp#257]
Ideas for API changes for 2.0:

 - Move everything to the `AMQP` namespace
   - `AMQP\Connection`, `AMQP\Exchange`, `AMQP\Queue`, etc.
 - Make constants class constants to make it easier to understand what options are present
   - E.g. `Exchange::DIRECT`, `Exchange::FANOUT`, `Queue::EXCLUSIVE`, `Queue::DURABLE` etc.
   - Add constant visibility
  - Get rid of `AMQP_NO_PARAM`, it’s weird
 - Move `AMQPQueue::declareQueue()` and `AMQPExchange::declareExchange()` to `AMQP\Channel::declare($queueOrExchange)`
   - A lot of libraries declare on the channel and it makes more sense semantically
- Require PHP 7.1
  - Add primitive type hints (nullable parameters supported)
  - Add return type hints (nullable parameters supported)
- Split callback registration, consumption and waiting
  - Right now `AMQPQueue::consume()` does all three (except if one passes null)
  - It would be nicer to be able to do something like this:
```php
$queue->consume(); // Start consuming the queue
$queue->handle(function() {...});
$queue->wait($timeout);
```

**Comment by lstrojny** [comment]
@pinepain I am sure you have plenty of good ideas as well. Looking forward for comments & more ideas.

**Comment by pinepain** [comment]
Looking at PHP supported versions roadmap (http://php.net/supported-versions.php), it seems to be that we could try to target PHP 7.1 as at the moment new php-amqp become  mature 7.0 might run into security fixes only stage and we will have to support both of them (which means reduced features number we can utilize). What do you think, @lstrojny and others?

**Comment by lstrojny** [comment]
@pinepain makes sense. That allows us to add type hints everywhere which is a nice side effect

**Comment by Tobion** [comment]
Currently symfony/messenger uses an interface to fetch messages from a "transport" (queue) that is `ReceiverInterface::get(): iterable`, see amqp implementation https://github.com/symfony/symfony/blob/2e5a8c80c6b4f906eee2c451a7e432b830775a98/src/Symfony/Component/Messenger/Transport/AmqpExt/AmqpReceiver.php#L42-L47
I think it's a good API but forces us to use basic.get on amqp instead of consume (which is blocking and requires a callback). I think it would be possible for AMQP extension to provide an API like `AMQPQueue::consume(): iterable` instead of `AMQPQueue::consume(callable $callback)`. It would return an iterable that blocks when no messages are available and that yields an `\AMQPEnvelope` when available. This would make it possible to implement blocking consume and non-blocking basic.get interchangably with the same API.
What do you think?

**Comment by pinepain** [comment]
@Tobion makes sense to me.

Regards 2.0 version API: I'm curious what would be the performance difference between C ext AMQP extension and the same code written in PHP using PHP 8.0 with JIT. Also, taking into account that FFI become a part of PHP 7.4 core, it may worth looking at it and see whether it could be used for extension and what would be the performance impact. The rationale behind this suggestions is to make contributing to extension and it development more accessible to wider audience, as currently there might be not too many people who are using this extension and could hack and slash in C (or willing to spend time on it).

**Comment by lstrojny** [comment]
Plans have changed, closing
